### ISSUE TITLE
Make upgradable

### ISSUE THREAD

**Issue by bitgamma** [status-im/status-keycard#13]
It became pretty clear, that the applet will need to be upgradable. At the moment this will be obtained by simply leaving the card with default Global Platform keys. However in the future we could use a key derived from the master wallet for upgrades (this means requiring a PIN to accept upgrading).

Upgrading removes the stored keys, PIN(s) etc. This means the procedure will not be as straightforward and will require backups. We must make sure upgrades are released only when strictly needed for introducing additional features. This also means that when we do a release we must be fairly sure that there are no bugs, especially security-related ones. This is currently achieved through extensive testing of all possible error conditions and malformed inputs.

**Comment by rileyg98** [comment]
There is an option you could consider: in general, you can use two applets to allow upgradability. One applet is the "back-end", as such, and it stores key material and PINs. The front-end, which is upgradable, can then just refer to the "back-end" applet to use the keys and PINs. Upgrades can occur without loss of data in this circumstance.

Otherwise, you can use chip-based keys (NXP for instance offers its PUF, which is a key derived from small differences in manufacture) to export and import backups only able to be decrypted by the chip in question.
