### ISSUE TITLE
Preloaded cryptocards in retail

### ISSUE THREAD

**Issue by guylouis** [status-im/status-keycard#20]
One of the main characteristic of smartcard-based hardwallets is their low cost. This kind of cards can be a very good support to trigger adoption of crypto-currencies for those who don’t want to go through an exchange to buy crypto. 

Some paper-wallets type of cards like ether.cards https://ether.cards/ offer this type of convenience by providing an already generated wallet, and will probably soon offer the same type of cards with a pre-paid amount of crypto on the wallet. We think that using a smartcard instead of a paper wallet for this type of scenarios could provide several security and convenience advantages.

In our current simple deployment scheme, the cards are delivered to the user without any wallet key pair. There is neither any specific mechanism already defined to uniquely identify each card.

There are two use cases that would make sense :

**1/ prepaid card** 
Our card is advertised as holding 50$ (example) of eth. The user buys this card in with 50$ of fiat in a store or online. When the user receives this card, he is guided (ideally through a secure tap-to-download an app feature) through an application (e.g. Status app) to activate his card, and his wallet is automatically filled with 50$ worth of crypto at the current exchange rate. 

**2/ empty card** 
Same scenario but sold in store. The user picks up a blank card, goes to the cashier, asks for the Fiat amount he wants to put on the card and the crypto type (« let me get 35$ of eth, please 🙂 « ). The cashier has a dedicated app on his phone, or a dedicated POS, cashes in the 35$ and provision the crypto in the card. 

Let’s brainstorm on what are the difficulties, and come up with a full system solution.

**Comment by ligi** [comment]
In scenario #1 ideally the card is a Faraday cage  (e.g. wrapped in aluminium foil) and sealed - to prevent trolls from bricking the cards.
Would also like to see scenario #1 with DAI instead of ETH (or a combination of both ETH for paying gas and DAI for spending)

**Comment by bitgamma** [comment]
Since scenario 1 can be most likely supported by a smart contract, it would nice to bring some smartcontract guys in the discussion.

**Comment by richard-ramos** [comment]
I think scenario 1 could be supported by something similar to the Hackathon Registration Dapp, meaning, if someone wants to buy a card with 50$, besides the card, he would receive a QR code that he could scan later in a dedicated dapp for the hardware wallet.

**Comment by jeluard** [comment]
I love @richard-ramos option!

2) sounds like a support nightmare

**Comment by bitgamma** [comment]
maybe an idea would be, instead of a QRcode to have a special applet for provisioning the ETH? It would be an applet with a private key (the public key would be known by the dapp) which could sign challenges coming from said dApp. QRCode would require unique code to printed on each package (somewhere were it cannot be seen without opening)

**Comment by richard-ramos** [comment]
Is the smart card able to sign a message that uniquely identifies the card?

**Comment by bitgamma** [comment]
yes, the card could sign its own unique ID

**Comment by ligi** [comment]
Let's please try to avoid QR codes ..-)

**Comment by richard-ramos** [comment]
@bitgamma If that's the case, I think the idea is doable. A smart contract could be created to give the $$ and keep track that it did that transaction when it received a message with a valid unique ID. 

Are these IDs registered somewhere?

**Comment by richard-ramos** [comment]
Indeed. We need to register somewhere the smart card IDs (individually or via merkle root) to guarantee it's a card that's allowed to withdraw funds. Can the fund amount change depending on the card? (Card A allows you to access 10$,  Card B, 50$)

**Comment by bitgamma** [comment]
Registering them individually is the best solution if not too resource 
expensive.

However, strictly speaking and only if resources/logistics do not allow 
tracking all issued cards, it would be possible to just register the public 
key for each category ($10, $20, etc). This would work because only our 
cards would have the correct private key to generate the claiming signature 
and we can trust our own card to not generate multiple IDs. Of course the 
claimed ID must be registered in any case to avoid the same card claiming 
multiple times. The disadvantage of this solution however is that if the 
private key is leaked, it becomes trivial to generate arbitrary IDs and 
signatures.

If we keep track instead of all issued cards it becomes much more difficult 
to attack even if the private key leaks, since it would become a brute 
force attack probably more expensive than minining.

Richard Ramos <notifications@github.com> 23 ноября 2018 г. 20:38:10 написал:
