### ISSUE TITLE
Pairing multiple devices?

### ISSUE THREAD

**Issue by alex-miller-0** [status-im/status-keycard#42]
I noticed your Keycard applet has a configurable number of [pairing slots](https://github.com/status-im/status-keycard/blob/add5da6ce8407d5e7144777646e28d1ec95adbb9/src/main/java/im/status/keycard/SecureChannel.java#L68), which is hardcoded to 5 [here](https://github.com/status-im/status-keycard/blob/add5da6ce8407d5e7144777646e28d1ec95adbb9/src/main/java/im/status/keycard/KeycardApplet.java#L36). This would imply you want to allow multiple pairings for a given card. 

> Aside: We at GridPlus actually discovered issues with this (namely, a user who tries to pair with a new device when the card is at its limit would be unable to use the card since only a paired device can unpair). We have implemented an [alternative](https://github.com/GridPlus/safe-card/pull/11/files) that simply overwrites the first pairing slot whenever a pairing is made - this is better for our use case.

However, it seems like a user can only pair if a `pairingSecret` is loaded (used [here](https://github.com/status-im/status-keycard/blob/master/src/main/java/im/status/keycard/SecureChannel.java#L231)) and the only way to load it is via the `INIT` command ([here](https://github.com/status-im/status-keycard/blob/add5da6ce8407d5e7144777646e28d1ec95adbb9/src/main/java/im/status/keycard/SecureChannel.java#L80) you can see the command getting blocked if `pairingSecret` has already been set).

Is this intentional? It seems odd to have the following both be true:

* 5 pairing slots
* Only the client that initializes the card can ever pair with it

Is there another way to allow pairing with multiple devices?

> Aside: We are working on a "re-init" function (PR [here](https://github.com/GridPlus/safe-card/pull/13)), which allows a new device to load its own `pairingSecret` *after* the card has been initialized. Of course this means that the old pairing will be invalid, but this is not a problem for us (see earlier `Aside`).

**Comment by bitgamma** [comment]
That's not exactly how it works. The pairingSecret is a key generated from an externally known secret. In our case is the PBKDF2 output of a password, but this is not enforced by the card.

When the card is uniniitalized it has no credentials, so no PIN/PUK/Pairing password. In this state the card accepts a pairing-less one-shot SecureChannel to bring the credentials on-card. The credentials can then be changed by the user at any time (all of them). Changing the pairingSecret does not break existing pairings, because the actual pairing key is different for each pairing and stored individually.

You can pair up to 5 devices at the same time, with the user inserting the pairing password on each. The entire pairing mechanism is needed to counter active MITM attacks and that's why an off-band secret is needed. Overwriting a slot would lock-out a previously paired device, that's why we do not allow it. Although that could be an option if implemented in a way which requires user interaction/authentication.

There are scenarios where pairing is not desired, such as at a POS. We already provided a subset of commands which can be executed without pairing.

**Comment by alex-miller-0** [comment]
Interesting. Can you point me to how a client can update the `pairingSecret`?

I do see how additional pairings can be made, but they seem to require knowledge of the `pairingSecret`, which I would assume shouldn't be passed from client to client.

**Comment by bitgamma** [comment]
Please check https://status.im/keycard_api/sdk_pinless.html about this

**Comment by alex-miller-0** [comment]
Got it, thanks for clarifying!
