### ISSUE TITLE
How to compile on linux? javacard 3 not available

### ISSUE THREAD

**Issue by anwfr** [status-im/status-keycard#50]
This project depends on javacard 3.0.4. It seems that javacard 3 is not available for Linux (last release for linux is 2.2.2).
Any hint to compile on linux?

**Comment by antonio-fr** [comment]
This can help if different from Oracle (windows jar) :
https://github.com/martinpaljak/oracle_javacard_sdks/tree/master/jc304_kit

Also there'a a "ant" system which looks easy and fast :
https://github.com/martinpaljak/ant-javacard

Similarly a javacard gradle plugin seems also interesting, "a wrapper on ant-javacard and Global Platform Pro, it is inspired by gradle-javacard" :
https://github.com/bertrandmartel/javacard-gradle-plugin

**Comment by bitgamma** [comment]
The included gradle file has already been tested on Mac and Linux, all you 
need is the JCDK files. If you want to use the official distribution you 
could install the Windows version of the JCDK on a Windows machine and copy 
the installation folder over to Linux (or use Wine). The Windows specific 
tools are not used to build Keycard so that won't be a problem.

antonio-fr <notifications@github.com> 15 мая 2019 г. 23:46:05 написал:

**Comment by anwfr** [comment]
Great! It worked by using javacard 3.0.4 files from https://github.com/martinpaljak/oracle_javacard_sdks/tree/master/jc304_kit
Thanks! :)
